#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Relay

# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

from cmk.notification_plugins.slack import slack_msg
from cmk.notification_plugins.utils import (collect_context, post_request, process_by_status_code)

def relay_msg(context):

    return { 
	'data': { 
        	'hostname'		: context['HOSTNAME'],
        	'host_address_4'	: context['HOST_ADDRESS_4'],
        	'service_desc'		: context['SERVICEDESC'],
        	'service_check_command'	: context['SERVICECHECKCOMMAND'],
        	'service_output'	: context['SERVICEOUTPUT'],
        	'service_perf_data'	: context['SERVICEPERFDATA'],
        	'date'			: context['DATE'],
         }
    }

if __name__ == "__main__":
    context = collect_context()
    api_token = context.get("PARAMETER_API_TOKEN")
    response = post_request(
	relay_msg, 
	url='https://api.relay.sh/api/events',
	headers={'Authorization': f'Bearer {api_token}' }
    )
   
    process_by_status_code(response, success_code = 202)



# vim: tabstop=4 shiftwidth=4 expandtab smarttab

